---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: xgeeks-ai-starter-demo
  annotations:
    secret.reloader.stakater.com/reload: "xgeeks-ai-starter-demo-dev-secrets,xgeeks-ai-starter-demo-dev-auth0-secrets"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: xgeeks-ai-starter-demo
  template:
    metadata:
      labels:
        app: xgeeks-ai-starter-demo
    spec:
      imagePullSecrets:
        - name: regcred-ghcr-io-secret
      initContainers:
        - name: xgeeks-ai-starter-demo-datafeeder
          image: ghcr.io/xgeekshq/xgeeks-ai-starter-demo-datafeeder
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: OPENAI_API_KEY
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: PINECONE_API_KEY
            - name: PINECONE_INDEX
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: PINECONE_INDEX
            - name: PINECONE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: PINECONE_ENVIRONMENT

          resources:
            requests:
              cpu: 125m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 500Mi
      containers:
        - name: xgeeks-ai-starter-demo
          image: ghcr.io/xgeekshq/xgeeks-ai-starter-demo
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 125m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 500Mi
          env:
            - name: NODE_ENV
              value: production
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: OPENAI_API_KEY
            - name: REPLICATE_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: REPLICATE_API_TOKEN
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: PINECONE_API_KEY
            - name: PINECONE_INDEX
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: PINECONE_INDEX
            - name: PINECONE_ENVIRONMENT
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-secrets
                  key: PINECONE_ENVIRONMENT
            - name: AUTH0_ISSUER_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-auth0-secrets
                  key: tenant
            - name: AUTH0_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: xgeeks-ai-starter-demo-dev-cm
                  key: AUTH0_BASE_URL
            - name: AUTH0_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-auth0-secrets
                  key: client_id
            - name: AUTH0_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-auth0-secrets
                  key: client_secret
            - name: AUTH0_SECRET
              valueFrom:
                secretKeyRef:
                  name: xgeeks-ai-starter-demo-dev-auth0-secrets
                  key: jwt_secret
            # - name: NEXT_PUBLIC_CLERK_SIGN_IN_URL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: xgeeks-ai-starter-demo-cm
            #       key: NEXT_PUBLIC_CLERK_SIGN_IN_URL
            # - name: NEXT_PUBLIC_CLERK_SIGN_UP_URL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: xgeeks-ai-starter-demo-cm
            #       key: NEXT_PUBLIC_CLERK_SIGN_UP_URL
            # - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: xgeeks-ai-starter-demo-cm
            #       key: NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL
            # - name: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
            #   valueFrom:
            #     configMapKeyRef:
            #       name: xgeeks-ai-starter-demo-cm
            #       key: NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL
            # - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: xgeeks-ai-starter-demo-dev-secrets
            #       key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
            # - name: CLERK_SECRET_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: xgeeks-ai-starter-demo-dev-secrets
            #       key: CLERK_SECRET_KEY
